### ISSUE TITLE
Can't change circle size

### ISSUE THREAD

**Issue by xpluscal** [ServusJon/SVGCircle-Module-for-FramerJS#3]
Hi there,

unfortunately I cannot change the diameter of the circle. Is this a known bug?

Best
C

**Comment by xpluscal** [comment]
Oh, I got it.
You had "circleWidth" in your Example not "circleSize"

**Comment by ServusJon** [comment]
Oh thank you! 
Do you mind making a pull request with the change?

**Comment by ServusJon** [comment]
Solved.
