### ISSUE TITLE
How to set the countdown goes on reverse

### ISSUE THREAD

**Issue by OskarMG** [ServusJon/SVGCircle-Module-for-FramerJS#4]
Hi, first I want to thank you for this nice prototype. Well, I want to make the countdown goes on reverse, for example: from 60 to 0, and when the animation finished, reset it again.

**Comment by ServusJon** [comment]
Thanks @OskarMG 

With the current implementation this could work:

loadingCircle.startAt(100)
Utils.delay 0.001, ->
	loadingCircle.changeTo(0, 2)
	loadingCircle.onFinished = ->
		loadingCircle.startAt(100)
