### ISSUE TITLE
Linear Easing not working?

### ISSUE THREAD

**Issue by mlaurita** [ServusJon/SVGCircle-Module-for-FramerJS#5]
Hey, 

It seems like no matter what I do, I can't get the circle to animate with a linear ease (it always has an easy-ease curve). Have tried setting "hasLinearEasing" to true, to no avail. Any ideas?

**Comment by ServusJon** [comment]
Should be solved now :-)

**Comment by mlaurita** [comment]
Amazing, thanks!
